### ISSUE TITLE
Error: java.io.FileNotFoundException for file leiningen.figwheel.clean-on-dependency-change

### ISSUE THREAD

**Issue by seacrawler11** [dtreskunov/dhis2-wdc#1]
Thanks for sharing this amazing piece of work. I attempted to set it up and received this below.
Note that my version is Leiningen 2.7.1 on Java 9-internal OpenJDK 64-Bit Server VM, thanks for your help.

uwa@ubuntu:~/dhis2-wdc$ lein figwheel
java.io.FileNotFoundException: /home/uwa/dhis2-wdc/target/stale/leiningen.figwheel.clean-on-dependency-change (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2)
    java.io.FileOutputStream.open (FileOutputStream.java:271)
    java.io.FileOutputStream.<init> (FileOutputStream.java:215)
    clojure.java.io$fn__9522.invokeStatic (io.clj:230)
    clojure.java.io/fn (io.clj:230)
    clojure.java.io$fn__9459$G__9428__9466.invoke (io.clj:69)
    clojure.java.io$fn__9496.invokeStatic (io.clj:166)
    clojure.java.io/fn (io.clj:166)
    clojure.java.io$fn__9472$G__9424__9479.invoke (io.clj:69)
    clojure.java.io$writer.invokeStatic (io.clj:119)
    clojure.java.io$writer.doInvoke (io.clj:104)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$spit.invokeStatic (core.clj:6668)
    clojure.core$spit.doInvoke (core.clj:6668)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    leiningen.figwheel$on_stamp_change.invokeStatic (figwheel.clj:185)
    leiningen.figwheel$on_stamp_change.invoke (figwheel.clj:180)
    leiningen.figwheel$clean_on_dependency_change.invokeStatic (figwheel.clj:192)
    leiningen.figwheel$clean_on_dependency_change.invoke (figwheel.clj:190)
    leiningen.figwheel$figwheel.invokeStatic (figwheel.clj:518)
    leiningen.figwheel$figwheel.doInvoke (figwheel.clj:436)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5932.doInvoke (main.clj:272)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

**Comment by seacrawler11** [comment]
It was due to java version. I downgraded from openjdk-9 to openjdk-8 and it built correctly. thanks

**Comment by dtreskunov** [comment]
Thanks for reporting (and resolving!) this issue. Currently, Clojure and ClojureScript are known to be incompatible with Java9. People are definitely working on adding support for it though:

https://github.com/technomancy/leiningen/issues/2149
https://github.com/tobias/clojure-java-9
