### ISSUE TITLE
Error: Please sign in

### ISSUE THREAD

**Issue by seacrawler11** [dtreskunov/dhis2-wdc#2]
the wdc successfully installed however I am getting a "Please sign in" error when I use it. A screenshot is attached. How do I resolve this? thanks in advance.

![dtc](https://cloud.githubusercontent.com/assets/9514046/24468989/e47bbd10-14b1-11e7-872a-f559ef5f2dc2.JPG)

**Comment by dtreskunov** [comment]
It works for me using the Demo credentials (admin / district per https://play.dhis2.org/demo).

"Please sign in" is displayed when the server returns HTTP 401 or 403 (Unauthorized). Not sure why it's happening. Try again please?

**Comment by dtreskunov** [comment]
Hi @seacrawler11 - I think I know what's causing it. The issue is that my CORS proxy is rejecting your requests.

* If you are hosting the connector on your own server: you'll need to set up your own CORS proxy (I recommend [cors-anywhere](https://cors-anywhere.herokuapp.com))
* If using it directly: please ensure you're accessing it via HTTPS, not HTTP (i.e. use https://dtreskunov.github.io/dhis2-wdc/, not ~~http://dtreskunov.github.io/dhis2-wdc/~~.

**Comment by seacrawler11** [comment]
Thanks for sharing this amazing tool and your time. It worked with a local CORS server. I can connect to DHIS Demo server. However, another issue has cropped up. When I connect to my DHIS server, I get a 404 error.

Response:
HTTP 404: <html>
 <head><title>404 Not Found</title></head>
 <body bgcolor="white">
 <center><h1>404 Not Found</h1></center>
 <hr><center>nginx/1.10.0 (Ubuntu)</center>
 </body>
 </html>


WDC Server is dtc.sc.local
DHIS server is dhis-backup.sc.local

NGINX log:
2017/04/01 16:02:06 [error] 1875#1875: *4 open() "/home/seacrawler/dhis2-wdc/resources/public/dhis-backup.sc.local/api/26/me" failed (2: No such file or directory), client: x.y.x.a, server: dtc.sc.local, request: "GET /wdc/dhis-backup.sc.local/api/26/me?fields=id&fields=displayName HTTP/1.1", host: 
"dtc.sc.local", referrer: "http://dtc.local.org/wdc/" 

the dhis server request is being passed to nginx which does not know what to do with them. I receive same 404 error when I use your hosted connector too. thanks for assisting.

**Comment by seacrawler11** [comment]
I have better understanding and it works. nginx's add_header X-Frame-Options security setting was protecting DHIS from attack. I have adjusted and it works. thanks for sharing and the support.
