### ISSUE TITLE
Select Dataset

### ISSUE THREAD

**Issue by seacrawler11** [dtreskunov/dhis2-wdc#3]
My default dataset contains archived data while another dataset has my current data. How do I select the current dataset? thankor another dataset? thanks

**Comment by dtreskunov** [comment]
Hi @seacrawler11 , currently, the connector does not support selecting datasets. Could you clarify what you mean by "select a dataset"? Is it simply to restrict the set of available dimensions? E.g. in the demo DHIS2 instance, there is a dataset for "ART monthly summary" that is associated with 123 data elements such as "ART clients with new adverse clinical event".

For my own reference, here are the endpoints:

```
GET https://play.dhis2.org/dev/api/26/dataSets
GET https://play.dhis2.org/dev/api/26/dataElements?filter=dataSetElements.dataSet.id:eq:lyLU2wR22tC
```
https://docs.dhis2.org/master/en/developer/html/dhis2_developer_manual_full.html

**Comment by seacrawler11** [comment]
Dear dtreskunov, this is what I mean. thanks for your help on this.
